
```{r}
library(reticulate)
library(tidyverse)
library(lubridate)
library(janitor)
library(readxl)
source('00_GlobalFunctions/functions.R')
source('01_WaterQuality/database-migration/03_future-formatting/import-functions.R')

# Path to main folder
fp_rel <- 'Water Quality/00 - Monthly Run Docs/Raw Field Data/Water Quality 2025/'

# Path to export folder
fp_export <- 'Water Quality/00 - Monthly Run Docs/Database Import Data/2025/'
```

```{python}
import os
import fitz

fp_rel = r.fp_rel

# Define path
def abs_path_emp(fp_rel=None):
    user_profile = os.environ.get('USERPROFILE')
    base_path = os.path.join(user_profile, 'California Department of Water Resources', 'Environmental Monitoring Program - Documents')
    if fp_rel:
        return os.path.normpath(os.path.join(base_path, fp_rel))
    return os.path.normpath(base_path)

fp_main = abs_path_emp(fp_rel)

# Extract VR pdf
def extract_VR(path):
    doc = fitz.open(path)
    form_fields = {}
    for page in doc:
        for widget in page.widgets():
            key = widget.field_name
            val = widget.field_value
            if key:
                form_fields[key] = val
    doc.close()
    return form_fields

# Store VR files
pdf_files = []
for root, dirs, files in os.walk(fp_main):
    for file in files:
        if (
            file.lower().endswith('.pdf') and 
            'van run field data sheet' in file.lower()
        ):
            full_path = os.path.join(root, file)
            pdf_files.append(full_path)
            print(full_path)
            
all_forms = []

for pdf_path in pdf_files:
  form_data = extract_VR(pdf_path)
  all_forms.append(form_data)
```

```{r warning=FALSE}
# Bring in VR files
vr_files <- py$all_forms

df_list <- list()

# Clean VR files
for (i in seq_along(vr_files)) {
  df_raw <- process_VR(vr_files[[i]])
  df_clean <- format_VR(df_raw)
  df_list[[i]] <- df_clean
}

df_VR_all <- do.call(rbind, df_list)

# Import FDS files
fp_xlsx <- list.files(path = abs_path_emp(fp_rel), pattern = '\\.xlsx$', recursive = TRUE, full.names = TRUE)

# Clean FDS files
df_FDS <- map_dfr(fp_xlsx, function(fp) {
  df_raw <- process_FDS(fp)
  format_FDS(df_raw)
})

# Combine
df_final <- bind_rows(df_VR_all, df_FDS)

# filter out extra rows
df_final <- df_final %>% filter(!(is.na(`Observed Property ID`) & `Result Value` == 'Yes'))
df_final <- df_final %>% filter(`Observed Property ID` != 'Water Depth')
```

```{r}
# Export by month
fp_export <- abs_path_emp(fp_export)

df_list <- split(df_final,
                 list(format(as.POSIXct(df_final$`Observed DateTime`), '%Y-%m')),
                 drop = TRUE)

invisible(lapply(names(df_list), function(name) {
  name_parts <- unlist(strsplit(name, '\\.'))
  year_month <- name_parts[1]

  fp_exp <- paste0(fp_export, '/', year_month,'_FDS_EMP-DWQ.csv')
  print(fp_exp)
  write_csv(df_list[[name]], file = fp_exp, na = '')
}))
```

