# Format EMP phyto data
## contact: Sarah Perry (sarah.perry@water.ca.gov)
```{r message = FALSE}
library(tidyverse)
library(fuzzyjoin)
library(lubridate)
'%!in%' <- function(x,y)!('%in%'(x,y))
```

## Read in data
```{r}
# read in data
df_syn <- read_csv('03_Phyto/PESP/data/EMP/Phyto Classification.csv', show_col_types = FALSE)
df_data <- read_csv('03_Phyto/PESP/data/EMP/Phyto Data 2008-present_012723.csv', show_col_types = FALSE)

# remove unnecessary columns/rename
df_data <- df_data %>%
  select(-c(Taxonomist, LabNumber, TIN, SynonymOrig)) %>%
  rename('Name' = 'Taxon')

# remove percents from percent col, fix dates/times, colony codes
df_data$Percent_Sample_Counted <- gsub('%','',df_data$Percent_Sample_Counted)
df_data$Colony_or_FilamentGroupCode[df_data$Colony_or_FilamentGroupCode == 'n/p'] <- NA_character_
df_data$SampleDate <- as.Date(df_data$SampleDate, format = '%m/%d/%Y')
df_data<- df_data %>%
  mutate(
    SampleTime = case_when(grepl(':', SampleTime) ~ SampleTime,
                           is.na(SampleTime) ~ NA_character_,
                           TRUE ~ paste0(substr(SampleTime, 1, nchar(SampleTime)-2),':',substr(SampleTime, nchar(SampleTime)-1, nchar(SampleTime)))
                           )
    )
```

## Standardize dataset
### Standardize station names
```{r}
df_data <- df_data %>%
  mutate(
    StationCode = case_when(StationCode == 'C3A-Hood' | StationCode == 'C3A - Hood' | StationCode == 'C3A Hood' ~ 'C3A',
                            StationCode == 'D16 - Twitchell' | StationCode == 'D16-Twitchell' |StationCode == 'D16 Twitchell' ~ 'D16',
                            StationCode == 'E22' ~ 'EZ2',
                            StationCode == 'E26' ~ 'EZ6',
                            StationCode == 'EZ2 SJR' | StationCode == 'EZ2 - SJR' ~ 'EZ2-SJR',
                            StationCode == 'EZ6 SJR' | StationCode == 'EZ6 - SJR' ~ 'EZ6-SJR',
                            TRUE ~ StationCode)
    )
```


### standardize "unknown" identifiers
```{r}
unknown_syns <- 'unknown|unidentified|Unidentified|Undetermined|undetermined'

df_data <- df_data %>%
  # update Taxon column to standardize Unknown
  mutate(
    Name = case_when(grepl(unknown_syns,Name,ignore.case = TRUE) ~ str_replace_all(Name, unknown_syns, 'Unknown'),
                      TRUE ~ Name)
    ) %>%
  # Update Genus column if unknown Species
  mutate(
    Genus = case_when(grepl('Unknown', Name) ~ 'Unknown',
                      is.na(Genus) ~ 'Unknown',
                      Genus == 'Other' ~ 'Unknown',
                      Genus == 'genus' ~ 'Unknown',
                      TRUE ~ Genus)
    ) %>%
  # Update Species column in unknown
  mutate(
      Species = case_when(Genus == 'Unknown' ~ 'Unknown',
                          is.na(Species) ~ 'Unknown',
                          TRUE ~ Species)
  )
```

### Add in higher level taxa/current names
```{r}
# subset synonym/taxon columns
df_syn <- df_syn %>% select(c('Kingdom':'AlgalGroup','CurrentName'))

# standardize spp. to sp.
df_data$Name <- str_replace_all(df_data$Name, 'spp.', 'sp.')
df_data$Species <- str_replace_all(df_data$Species, 'spp.', 'sp.')

# standardize unknown names before synonym join
df_data <- df_data %>%
  mutate(
    Name = case_when(Name == 'LGBs' ~ 'Little Green Balls',
                     Name == 'Unknown Banana Blue Green' | Name == 'Unknown Cyanobacteria sp.' ~ 'Unknown cyanobacterium',
                     Name == 'Unknown centrales sp.' | Name == 'Unknown centric sp.' | Name == 'Unknown Centric diatom'  ~ 'Unknown centric diatom',
                     Name == 'Unknown Chlorophyte alga sp.' | Name == 'Unknown Chlorophyte filament' ~ 'Unknown green alga',
                     Name == 'Unknown dinoflagellate sp.' | Name == 'Unknown Dinoflagellate sp.' | Name == 'small dinoflagellates'~ 'Unknown dinoflagellate',
                     Name == 'Unknown girdle sp.' | Name == 'Unknown pennales sp.' | Name == 'Unknown pennate girdle sp.' ~ 'Unknown pennate diatom',
                     Name == 'Small nano-flagellates' | Name == 'small nano-flagellates' ~ 'Unknown nanoflagellate',
                     Name == 'Unknown Euglenoids' ~ 'Unknown euglenoid',
                     Name == 'Unknown Genus' ~ 'Unknown genus',
                     TRUE ~ Name)
    )

# join with main dataset
df_joined <- df_data %>%
  left_join(df_syn, by = 'Name') %>%
  mutate(Genus = Genus.y) %>%
  select(-c(ends_with('.y'), ends_with('.x'))) %>%
  relocate(c(Name, Kingdom:AlgalGroup), .after = StationCode) %>%
  relocate(c(Genus, Species), .after = AlgalGroup)
```

### Update Names
```{r}
# TODO: flag if species is > 1 word to check manually
# TODO: so many functions
df_joined <- df_joined %>%
  mutate(
    Genus = case_when(Name == CurrentName | grepl('None|Unknown',CurrentName) | is.na(CurrentName) ~ Genus,
                      TRUE ~ str_remove(str_squish(str_remove(CurrentName, 'cf.')), ' .*')),
    Species = case_when(Name == CurrentName | grepl('None|Unknown',CurrentName) | is.na(CurrentName) ~ Species,
                        TRUE ~ str_remove(str_squish(str_remove(CurrentName, 'cf.')), '.*? ')),
    OrigName = case_when(Name == CurrentName | grepl('None|Unknown',CurrentName) | is.na(CurrentName) ~ NA_character_,
                         TRUE ~ Name),
    Name = case_when(grepl('None|Unknown',CurrentName) | is.na(CurrentName) ~ Name,
                      TRUE ~ CurrentName
                      )) %>%
  select(-CurrentName) %>%
  relocate(OrigName, .after = StationCode)

# standardize specific unknown name cases
df_joined <- df_joined %>%
  mutate(
    AlgalGroup = case_when(Name == 'Little Green Balls' ~ 'Unknown',
                           Name == 'Unknown cyanobacteria' ~ 'Cyanobacteria',
                           Name == 'Unknown centric diatom' ~ 'Centric Diatoms',
                           Name == 'Unknown green alga' ~ 'Green Algae',
                           Name == 'Unknown dinoflagellate' ~ 'Dinoflagellates',
                           Name == 'Unknown pennate diatom' ~ 'Pennate Diatoms',
                           Name == 'Unknown nanoflagellate' ~ 'Nanflagellates',
                           Name == 'Unknown euglenoid' ~ 'Euglenoids',
                           TRUE ~ AlgalGroup)
  )
```

### Check taxa for errors
```{r}
df_error_check <- df_joined %>% select(c('Name':'Species'))

check <- df_error_check %>% subset(is.na(AlgalGroup) | is.na(Class) | is.na(Phylum) | is.na(Kingdom) | is.na(Genus) | is.na(Species))
check <- check[!duplicated(check),]
check <- check %>% arrange(Name)
syn_check <- df_error_check %>% subset(is.na(Name) | Name == 'Unknown')
syn_check <- syn_check[!duplicated(syn_check),]
syn_check <- syn_check %>% arrange(Name)

print(check)
print(syn_check)
```

## Clean Data
### Average Biovolume, Biovolume Density
```{r}
df_joined <- df_joined %>%
  mutate(AverageBiovolume = round(rowMeans(select(., starts_with('Biovolume')), na.rm = TRUE),2),
         AverageBiovolume_per_mL = round(AverageBiovolume/VolumeAnalyzed,2)) %>%
  select(-starts_with('Biovolume_')) %>%
  relocate(Comments, .after = Shape) %>%
  relocate(AverageBiovolume:AverageBiovolume_per_mL, .after = Organisms_per_mL)

df_joined$AverageBiovolume[is.nan(df_joined$AverageBiovolume)] <- NA
df_joined$AverageBiovolume_per_mL[is.nan(df_joined$AverageBiovolume_per_mL)] <- NA
```

### Change Comments to QA
```{r}
df_joined <- df_joined %>%
  mutate(
    QC_1 = case_when(grepl('broken\\.|cannot meet|did not reach|delete', Comments, ignore.case = TRUE) ~ 'BadData'),
    QC_2 = case_when(grepl('degraded', Comments, ignore.case = TRUE) ~ 'Degraded'),
    QC_3 = case_when(grepl('poorly preserved', Comments, ignore.case = TRUE) ~ 'PoorlyPreserved'),
    QC_4 = case_when(grepl('fragment\\.', Comments, ignore.case = TRUE) ~ 'Fragmented')
  ) %>%
  unite(QualityCheck, starts_with('QC'), remove = TRUE, na.rm = TRUE, sep = ' ')

df_joined$QualityCheck[df_joined$QualityCheck == ''] <- 'Good'
```

### Remove Columns and Duplicates
```{r}
df_joined <- df_joined %>%
  select(-c(VolumeReceived:UnitAbundance, Cells_per_Unit, Total_Cells_Counted, Comments))

df_joined <- distinct(df_joined)
df_joined <- df_joined[!duplicated(df_joined),]
```

## Export
```{r}
write_csv(df_joined,'03_Phyto/PESP/data/EMP/EMP_Phyto_Data_2008-2021.csv')
```

