### Excel FDS Data Formatting

Format data from Excel FDS for import into Aquarius Samples Database

*Questions: sarah.perry\@water.ca.gov*

------------------------------------------------------------------------

#### Define file paths

Path to import folder

```{r}
# Path to import folder
fp_import <- 'Water Quality/00 - Monthly Run Docs/Raw Field Data/Water Quality 2019-2024/Water Quality 2024/03 - March'
```

Path to export folder

```{r}
# Path to export folder
fp_export <- 'Water Quality/00 - Monthly Run Docs/Database Import Data/2024/'
```

------------------------------------------------------------------------

#### Run next three blocks *without edits*

***Note:** requires both R and Python*

```{r}
library(reticulate)
library(tidyverse)
library(lubridate)
library(janitor)
library(readxl)
source('00_GlobalFunctions/functions.R')
source('01_WaterQuality/01_routine/aquarius/aquarius_functions/import-functions.R')
```

```{python}
from os import environ, walk
from os.path import join, normpath, basename
import fitz

# Bring in import fp
fp_import = r.fp_import

# Define function to sanitize Excel imports later
def sanitize_excel(xlsx_path, csv_path):
  from openpyxl import load_workbook
  import csv
  wb = load_workbook(xlsx_path, data_only=True)
  ws = wb.active
  with open(csv_path, 'w', newline='') as f:
    writer = csv.writer(f)
    for row in ws.iter_rows(values_only=True):
      writer.writerow([str(v) if v is not None else '' for v in row])

# Define path
def abs_path_emp(fp_import=None):
    user_profile = environ.get('USERPROFILE')
    base_path = join(user_profile, 'California Department of Water Resources', 'Environmental Monitoring Program - Documents')
    if fp_import:
        return normpath(join(base_path, fp_import))
    return normpath(base_path)

fp_main = abs_path_emp(fp_import)

# Extract VR pdf
def extract_VR(path):
    doc = fitz.open(path)
    form_fields = {}
    for page in doc:
        for widget in page.widgets():
            key = widget.field_name
            val = widget.field_value
            if key:
                form_fields[key] = val
    doc.close()
    return form_fields

# Store VR files
pdf_files = []
for root, dirs, files in walk(fp_main):
    for file in files:
        if (
            file.lower().endswith('.pdf') and
            (
              'van run field data sheet' in file.lower() or
             '_main' in file.lower()
            )
        ):
            full_path = join(root, file)
            pdf_files.append(full_path)


print('pdf files used:', *[basename(p) for p in pdf_files], sep='\n  - ')

all_forms = []

for pdf_path in pdf_files:
  form_data = extract_VR(pdf_path)
  all_forms.append(form_data)
```

```{r warning=FALSE}
# Bring in VR files   
vr_files <- py$all_forms

df_list <- list()

# Clean VR files
for (i in seq_along(vr_files)) {
  df_raw <- process_VR(vr_files[[i]])
  df_clean <- format_VR(df_raw)
  df_list[[i]] <- df_clean
}

df_VR_all <- do.call(rbind, df_list)

# Import FDS files
fp_xlsx <- list.files(path = abs_path_emp(fp_import), pattern = '\\.xlsx$', recursive = TRUE, full.names = TRUE)

fp_csv <- map_chr(fp_xlsx, function(fp) {
  csv_path <- tempfile(fileext = '.csv')
  reticulate::py$sanitize_excel(fp, csv_path)
  csv_path
})


# Clean FDS files
df_FDS <- map_dfr(fp_csv, function(fp) {
  df_raw <- process_FDS_csv(fp)
  # format_FDS_csv(df_raw)
})

# Combine
df_final <- bind_rows(df_VR_all, df_FDS)

# Filter out extra rows
df_final <- df_final %>% filter(!(is.na(`Observed Property ID`) & `Result Value` == 'Yes'))
df_final <- df_final %>% filter(`Observed Property ID` != 'Water Depth')
```

------------------------------------------------------------------------

#### Data Checks

Check stations

```{r}
# check stations
check_stations(df_final)
```

Check for any extra data

```{r}
# check extra data
check_extra_data(df_final)
```

Check filter container ID is properly formatted

```{r}
# check filter container ID
check_filter_ID(df_final)
```

Check all analytes are accounted for

```{r}
# check analytes
check_analytes(df_final, type = 'field')
```

------------------------------------------------------------------------

#### Export file(s)

```{r}
# # Export by month
fp_export <- abs_path_emp(fp_export)

df_list <- split(df_final,
                 list(format(as.POSIXct(df_final$`Observed DateTime`), '%Y-%m')),
                 drop = TRUE)

invisible(lapply(names(df_list), function(name) {
  name_parts <- unlist(strsplit(name, '\\.'))
  year_month <- name_parts[1]

  fp_exp <- paste0(fp_export, '/', year_month,'_FDS_EMP-DWQ.csv')
  write_csv(df_list[[name]], file = fp_exp, na = '')
}))
```
