# Intial clean of EMP Phyto Data
# Update: 06/23, add cell/ml

```{r message = FALSE}
library(tidyverse)
library(fuzzyjoin)
library(lubridate)
'%!in%' <- function(x,y)!('%in%'(x,y))
```

## Read in data
```{r}
# read in data
df_syn <- read_csv('03_Phyto/PESP/data/EMP/Phyto Classification.csv', show_col_types = FALSE) # synonym list for comparison
df_data <- read_csv('03_Phyto/PESP/data/EMP/Phyto Data 2008-present_012723.csv', show_col_types = FALSE) # raw data

# remove unnecessary columns/rename
df_data <- df_data %>%
  select(-c(Taxonomist, LabNumber, TIN, SynonymOrig))

# remove percents from percent col, fix dates/times, colony codes
df_data$Percent_Sample_Counted <- gsub('%','',df_data$Percent_Sample_Counted)
df_data$Colony_or_FilamentGroupCode[df_data$Colony_or_FilamentGroupCode == 'n/p'] <- NA_character_
df_data$SampleDate <- as.Date(df_data$SampleDate, format = '%m/%d/%Y')
df_data<- df_data %>%
  mutate(
    SampleTime = case_when(grepl(':', SampleTime) ~ SampleTime,
                           is.na(SampleTime) ~ NA_character_,
                           TRUE ~ paste0(substr(SampleTime, 1, nchar(SampleTime)-2),':',substr(SampleTime, nchar(SampleTime)-1, nchar(SampleTime)))
                           )
    )
```

## Standardize dataset
### Standardize station names
```{r}
df_data <- df_data %>%
  mutate(
    StationCode = case_when(StationCode == 'C3A-Hood' | StationCode == 'C3A - Hood' | StationCode == 'C3A Hood' ~ 'C3A',
                            StationCode == 'D16 - Twitchell' | StationCode == 'D16-Twitchell' |StationCode == 'D16 Twitchell' ~ 'D16',
                            StationCode == 'E22' ~ 'EZ2',
                            StationCode == 'E26' ~ 'EZ6',
                            StationCode == 'EZ2 SJR' | StationCode == 'EZ2 - SJR' ~ 'EZ2-SJR',
                            StationCode == 'EZ6 SJR' | StationCode == 'EZ6 - SJR' ~ 'EZ6-SJR',
                            TRUE ~ StationCode)
    )
```


### standardize "unknown" identifiers
```{r}
unknown_syns <- 'unknown|unidentified|Unidentified|Undetermined|undetermined'

df_data <- df_data %>%
  # update Taxon column to standardize Unknown
  mutate(
    Taxon = case_when(grepl(unknown_syns,Taxon,ignore.case = TRUE) ~ str_replace_all(Taxon, unknown_syns, 'Unknown'),
                      TRUE ~ Taxon)
    ) %>%
  # Update Genus column if unknown Species
  mutate(
    Genus = case_when(grepl('Unknown', Taxon) ~ 'Unknown',
                      is.na(Genus) ~ 'Unknown',
                      Genus == 'Other' ~ 'Unknown',
                      Genus == 'genus' ~ 'Unknown',
                      TRUE ~ Genus)
    ) %>%
  # Update Species column in unknown
  mutate(
      Species = case_when(Genus == 'Unknown' ~ 'Unknown',
                          is.na(Species) ~ 'Unknown',
                          TRUE ~ Species)
  )
```

### Add in higher level taxa/current names
```{r}
# subset synonym/taxon columns
df_syn <- df_syn %>% select(c('Kingdom':'AlgalGroup','Taxon','CurrentTaxon'))

# standardize spp. to sp.
df_data$Taxon <- str_replace_all(df_data$Taxon, 'spp.', 'sp.')
df_data$Species <- str_replace_all(df_data$Species, 'spp.', 'sp.')

# standardize unknown names before synonym join
df_data <- df_data %>%
  mutate(
    Taxon = case_when(Taxon == 'LGBs' ~ 'Little Green Balls',
                     Taxon == 'Unknown Banana Blue Green' | Taxon == 'Unknown Cyanobacteria sp.' ~ 'Unknown cyanobacterium',
                     Taxon == 'Unknown centrales sp.' | Taxon == 'Unknown centric sp.' | Taxon == 'Unknown Centric diatom'  ~ 'Unknown centric diatom',
                     Taxon == 'Unknown Chlorophyte alga sp.' | Taxon == 'Unknown Chlorophyte filament' ~ 'Unknown green alga',
                     Taxon == 'Unknown dinoflagellate sp.' | Taxon == 'Unknown Dinoflagellate sp.' | Taxon == 'small dinoflagellates'~ 'Unknown dinoflagellate',
                     Taxon == 'Unknown girdle sp.' | Taxon == 'Unknown pennales sp.' | Taxon == 'Unknown pennate girdle sp.' ~ 'Unknown pennate diatom',
                     Taxon == 'Small nano-flagellates' | Taxon == 'small nano-flagellates' ~ 'Unknown nanoflagellate',
                     Taxon == 'Unknown Euglenoids' ~ 'Unknown euglenoid',
                     Taxon == 'Unknown Genus' ~ 'Unknown genus',
                     Taxon == 'Unknown Algae' ~ 'Unknown',
                     TRUE ~ Taxon)
    )

# join with main dataset
df_joined <- df_data %>%
  left_join(df_syn, by = 'Taxon') %>%
  # mutate(Genus = Genus.y) %>%
  select(-c(ends_with('.y'), ends_with('.x'))) %>%
  relocate(c(Taxon, Kingdom:AlgalGroup), .after = StationCode) %>%
  relocate(c(Genus, Species), .after = AlgalGroup)

# figure out switching to military time (add)
# df_joined$SampleTime <- format(strptime(df_joined$SampleTime, "%I:%M"), format="%H:%M")
```

### Update Names
```{r}
# TODO: flag if species is > 1 word to check manually
# TODO: so many functions
df_joined <- df_joined %>%
  mutate(
    Genus = case_when(Taxon == CurrentTaxon | grepl('None|Unknown',CurrentTaxon) | is.na(CurrentTaxon) ~ Genus,
                      TRUE ~ str_remove(str_squish(str_remove(CurrentTaxon, 'cf.')), ' .*')),
    Species = case_when(Taxon == CurrentTaxon | grepl('None|Unknown',CurrentTaxon) | is.na(CurrentTaxon) ~ Species,
                        TRUE ~ str_remove(str_squish(str_remove(CurrentTaxon, 'cf.')), '.*? ')),
    OrigTaxon = case_when(Taxon == CurrentTaxon | grepl('None|Unknown',CurrentTaxon) | is.na(CurrentTaxon) ~ NA_character_,
                         TRUE ~ Taxon),
    Taxon = case_when(grepl('None|Unknown',CurrentTaxon) | is.na(CurrentTaxon) ~ Taxon,
                      TRUE ~ CurrentTaxon
                      )) %>%
  select(-CurrentTaxon) %>%
  relocate(OrigTaxon, .after = StationCode)

# standardize specific unknown Taxon cases
df_joined <- df_joined %>%
  mutate(
    AlgalGroup = case_when(Taxon == 'Little Green Balls' ~ 'Unknown',
                           Taxon == 'Unknown cyanobacteria' ~ 'Cyanobacteria',
                           Taxon == 'Unknown centric diatom' ~ 'Centric Diatoms',
                           Taxon == 'Unknown green alga' ~ 'Green Algae',
                           Taxon == 'Unknown dinoflagellate' ~ 'Dinoflagellates',
                           Taxon == 'Unknown pennate diatom' ~ 'Pennate Diatoms',
                           Taxon == 'Unknown nanoflagellate' ~ 'Nanflagellates',
                           Taxon == 'Unknown euglenoid' ~ 'Euglenoids',
                           TRUE ~ AlgalGroup)
  )
```

### Check taxa for errors
```{r}
df_error_check <- df_joined %>% select(c('Taxon':'Species'))

check <- df_error_check %>% subset(is.na(AlgalGroup) | is.na(Class) | is.na(Phylum) | is.na(Kingdom) | is.na(Genus) | is.na(Species))
check <- check[!duplicated(check),]
check <- check %>% arrange(Taxon)
syn_check <- df_error_check %>% subset(is.na(Taxon) | Taxon == 'Unknown')
syn_check <- syn_check[!duplicated(syn_check),]
syn_check <- syn_check %>% arrange(Taxon)

print(check)
print(syn_check)
```

## Clean Data
### Average Biovolume, Biovolume Density
```{r}
df_joined$Total_Cells_Counted <- as.numeric(df_joined$Total_Cells_Counted)

df_joined <- df_joined %>%
  mutate(Cells_per_mL =
    case_when(
      Lab == 'EcoAnalysts' ~ Organisms_per_mL*Cells_per_Unit,
      Lab == 'BSA' ~ Total_Cells_Counted*Factor)
  )

df_joined <- df_joined %>%
  mutate(AverageBiovolume = round(rowMeans(select(., starts_with('Biovolume')), na.rm = TRUE),2),
         AverageBiovolume_per_mL = round(AverageBiovolume*Factor*Total_Cells_Counted,2)) %>% # Counted'
  select(-starts_with('Biovolume_')) %>%
  relocate(Comments, .after = Shape) %>%
  relocate(AverageBiovolume:AverageBiovolume_per_mL, .after = Organisms_per_mL)

df_joined$AverageBiovolume[is.nan(df_joined$AverageBiovolume)] <- NA
df_joined$AverageBiovolume_per_mL[is.nan(df_joined$AverageBiovolume_per_mL)] <- NA
```

### Change Comments to QA
```{r}
df_joined <- df_joined %>%
  mutate(
    QC_1 = case_when(grepl('broken\\.|cannot meet|did not reach|delete', Comments, ignore.case = TRUE) ~ 'BadData'),
    QC_2 = case_when(grepl('degraded', Comments, ignore.case = TRUE) ~ 'Degraded'),
    QC_3 = case_when(grepl('poorly preserved', Comments, ignore.case = TRUE) ~ 'PoorlyPreserved'),
    QC_4 = case_when(grepl('fragment\\.', Comments, ignore.case = TRUE) ~ 'Fragmented')
  ) %>%
  unite(QualityCheck, starts_with('QC'), remove = TRUE, na.rm = TRUE, sep = ' ')

df_joined$QualityCheck[df_joined$QualityCheck == ''] <- 'Good'
```

### Remove Columns and Duplicates
```{r}
df_joined <- df_joined %>%
  select(-c(VolumeReceived:UnitAbundance, Cells_per_Unit, Total_Cells_Counted, Comments))

df_joined <- distinct(df_joined)
df_joined <- df_joined[!duplicated(df_joined),]
```

## Export
```{r}
write_csv(df_joined,'03_Phyto/PESP/data/EMP/EMP_Phyto_Data_2008-2021_CELLSADDITION063023.csv')
```
# ------
# ADD IN CELL/ML
# ------

```{r message=FALSE}
df_edi <- read_csv('03_Phyto/PESP/data/EMP/phytoedi_2022_wcoords.csv')
df_newcells <- read_csv('03_Phyto/PESP/data/EMP/EMP_Phyto_Data_2008-2021_CELLSADDITION063023.csv')
```

```{r}
library(tidylog)
df_newcells <- df_newcells %>% subset(select = c('Taxon','SampleDate','StationCode','Organisms_per_mL','Cells_per_mL','Shape','AverageBiovolume_per_mL'))
df_edi$SampleDate <- as.Date(df_edi$SampleDate, '%m/%d/%Y')
df_newcells$SampleDate <- as.Date(df_newcells$SampleDate, '%m/%d/%Y')
df_edi <- df_edi %>% rename(Taxon = Name) %>% rename(OrigTaxon = OrigName)

# checks; all should be false before merging
unique(!(df_edi$Taxon == df_newcells$Taxon))
unique(!(df_edi$SampleDate == df_newcells$SampleDate))
unique(!(df_edi$StationCode == df_newcells$StationCode))
unique(!(df_edi$Organisms_per_mL == df_newcells$Organisms_per_mL))
unique(!(df_edi$Shape == df_newcells$Shape))
unique(!(df_edi$AverageBiovolume_per_mL == df_newcells$AverageBiovolume_per_mL))


df_check <- anti_join(df_edi, df_newcells, by = c('Taxon','SampleDate','StationCode','Organisms_per_mL','Shape','AverageBiovolume_per_mL'))

df_export <- left_join(df_edi, df_newcells, by = c('Taxon','SampleDate','StationCode','Organisms_per_mL','Shape','AverageBiovolume_per_mL'))

df_export <- df_export %>% relocate('Cells_per_mL', .after = 'Organisms_per_mL') %>%
  select (-'AverageBiovolume') %>%
  rename('Taxon' = 'Taxon') %>%
  rename('OrigTaxon' = 'OrigTaxon')

nrow(df_edi) == nrow(df_newcells)
nrow(df_export) == nrow(df_newcells)

write_csv(df_export, '03_Phyto/PESP/data/EMP/phytoedi_2022_wcellscoords.csv')
```


