---
title: "EMP Station History"
author: "Ted Flynn"
date: "2024-06-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(lubridate)))
suppressWarnings(suppressMessages(library(janitor)))
suppressWarnings(suppressMessages(library(here)))
suppressWarnings(suppressMessages(library(cder)))

# Set output directory 
output <- here("04_Other","EMP-station-history","output")

# Set visual theme in ggplot
theme_set(theme_bw())

# Suppress summarise info
options(tidyverse.quiet = TRUE)
options(dplyr.summarise.inform = FALSE)

# Create date variables for CDEC import-----------------------------------------
start <- as.Date("1980-01-01")
end <- Sys.Date()

```

## Import Data from Discrete Components
```{r discrete, echo=FALSE}
# Import phytoplankton data ----------------------------------------------------
# Start with CSV sent by Tiffany with historical data (2007 and earlier)
df_phyto <- read_csv(file = here("04_Other",
                                 "EMP-station-history",
                                 "data",
                                 "phyto-dates-and-stations.csv"), 
                     show_col_types = FALSE)

# Rename headers to match others and convert dates
df_phyto <- df_phyto %>% 
  rename("Date" = "SampleDate") %>% 
  rename("StationID" = "StationCode") %>% 
  mutate(Date = mdy(Date)) %>% 
  mutate(Year = year(Date))

# Read in more recent phyto data from 2008 onwards (from EDI)
df_phyto_EDI <- read_csv(file = here("04_Other",
                                     "EMP-station-history",
                                     "data",
                                     "EMP_Phyto_Data_2008-present.csv"),
                         show_col_types = FALSE) %>% 
  mutate(Date = mdy(Date)) %>% 
  mutate(Year = year(Date)) %>% 
  rename("StationID" = "Station")

# Import discrete Water quality data -------------------------------------------
# Read in CSV downloaded from EDI (data through 2022)
df_DWQ <- read_csv(file = here("04_Other",
                   "EMP-station-history",
                   "data",
                   "EMP_DWQ_1975_2022.csv"),
                   show_col_types = FALSE) %>% 
  mutate(Year = year(Date)) %>% 
  rename("StationID" = "Station")

# Import zooplankton data ------------------------------------------------------
# Read in CSV downloaded from EDI (data through 2021)
# Use Clarke-Bumpus data (maybe check if other records are more complete later)
df_zoop <- read_csv(file = here("04_Other",
                                "EMP-station-history",
                                "data",
                                "cb_matrix.csv"), 
                    show_col_types = FALSE)

# Select columns needed, rename headers to match others and convert dates
df_zoop <- df_zoop %>% 
  select(SampleDate,Year,StationNZ,DWRStationNo) %>% 
  rename("Date" = "SampleDate") %>% 
  rename("StationID" = "DWRStationNo")

# Update DWR Station IDs where they are missing from zoop metadata
df_zoop <- df_zoop %>% 
  mutate(StationID = case_when(StationNZ == "NZD14" ~ "D14A",
                               StationNZ == "NZM06" ~ "MD6",
                               StationNZ == "NZM07" ~ "MD7",
                               StationNZ == "NZ040" ~ "D9",
                               StationNZ == "NZD11" ~ "D11",
                               StationNZ == "NZD15" ~ "D15",
                               StationNZ == "NZP10" ~ "P10",
                               TRUE ~ StationID)) # only 1973

# Remove non-compliance zooplankton stations
df_zoop <- df_zoop %>%
  filter(!is.na(StationID)) %>% 
  select(!StationNZ)

# Import benthic invert data ---------------------------------------------------
# Import CPUE data downloaded from EDI (current through 2023)
df_ben <- read_csv(file = here("04_Other",
                               "EMP-station-history",
                               "data",
                               "DWR Benthic CPUE data 1975-2023.csv"), 
                   show_col_types = FALSE)



# Select columns needed, rename headers to match others
df_ben <- df_ben %>% 
  select(SampleDate,Year,StationCode) %>% 
  rename("StationID" = "StationCode")

```

## Import Continuous WQ Data from CDEC
```{r import continuous, echo=TRUE}
# Import list of all compliance stations with additional metadata
df_stations <- read_csv(file = here("04_Other",
                                    "EMP-station-history",
                                    "compliance-station-names.csv"),
                        show_col_types = FALSE)

# Make list of all compliance stations and remove NAs
test_stations <- unique(df_stations$CDEC)
test_stations <- na.omit(test_stations)

last_stations <- c("GYS","BDL","NSL","IBS","BKS","TRN","FPT","ROR")

# Download WQ station data from CDEC and summarize by Year ---------------------
# First create a blank data frame to store CDEC data
df_CWQ_all <- as_tibble(
  data.frame(
    StationID = character(),
    Year = numeric(),
    Month = character(),
    SensorNumber = numeric(),
    SensorType = character(),
    Duration = character(),
    DailyMean = numeric()
  )
)

# df_temp <- cdec_query(stations = test_stations, 
#                       sensors = c(5,100,25,146,27,221,28,61,62),
#                       start.date = start,
#                       end.date = end)

# Download only EC and WT data (most common)
for (x in last_stations) {
  
  # Query each station one at a time
  df_temp <- cdec_query(x, 
                        sensors = c(5,100,25,146,27,221,28,61,62),
                        start.date = start,
                        end.date = end)
  
  df_temp <- df_temp %>% 
    select(StationID:DateTime,Value)
  
  # Summarize data record for EMP
  df_temp <- df_temp %>%
    filter(!is.na(Value)) %>% 
    mutate(Year = year(DateTime)) %>%
    mutate(Month = month(DateTime, label = TRUE)) %>% 
    mutate(Date = date(DateTime)) %>% 
    group_by(StationID,Year,Month,Date,SensorNumber,SensorType,Duration) %>% 
    summarise(Measurements = n(),
              DailyMean = mean(Value)) %>%
    ungroup()
  
  df_CWQ_all <- bind_rows(df_CWQ_all, df_temp)
  
  rm(df_temp)
  
}

# Create copy to modify
df_WQ <- df_CWQ_all

# Remove years with < 10 total measurements stations that aren't monitored
# df_WQ <- df_WQ %>% filter(Measurements > 10)

# Save df for use in other scripts
save(df_CWQ_all, 
     file = here("04_Other",
     "EMP-station-history",
     "CDEC-station-data-all.RData"))
```

## QC on Continuous WQ Data
```{r CWQ QC, echo=FALSE}
# After doing above 1X, just import continuous WQ data downloaded from EDI
# Import list of all compliance stations with additional metadata
df_stations <- read_csv(file = here("04_Other",
                                    "EMP-station-history",
                                    "compliance-station-names.csv"),
                        show_col_types = FALSE)

load(file = here("04_Other",
                 "EMP-station-history",
                 "CDEC-station-data-all.RData"))

# Remove negative and zero values
# Remove clearly erroneous values, like water temp > 100 or SpC > 100,000
df_CWQ <- df_CWQ_all %>% 
  filter(DailyMean > 0) %>% 
  filter(!(SensorType == "TEMP W" & DailyMean > 100)) %>% 
  filter(!(SensorType == "TEMP W" & DailyMean <= 32)) %>%
  filter(!(SensorType == "EL COND"& DailyMean > 100000))

df_CWQ %>% 
  filter(StationID %in% c("ANH")) %>% 
  ggplot(aes(x = Date, y = DailyMean, color = Duration)) + 
  geom_point() +
  facet_wrap(~ SensorType, ncol = 3, scales = "free_y")

test <- df_CWQ %>% 
  filter(StationID %in% c("CLL") & SensorType %in% c("EL CND", "EL COND"))

df_CLL_ANH <- cdec_query(c("CLL","ANH") , 
                        sensors = c(5,100),
                        start.date = ymd("1985-01-01"),
                        end.date = ymd("2000-01-01"))

```


```{r load continuous, echo=TRUE}
# After doing above 1X, just import continuous WQ data downloaded from EDI
# Import list of all compliance stations with additional metadata
df_stations <- read_csv(file = here("04_Other",
                                    "EMP-station-history",
                                    "compliance-station-names.csv"),
                        show_col_types = FALSE)

load(file = here("04_Other",
                 "EMP-station-history",
                 "CDEC-station-history.RData"))

# Add missing Combined Station Metadata
df_CWQ <- left_join(df_CWQ,
                    df_stations %>% 
                      select(CombinedID,CDEC) %>% 
                      distinct(),
                    join_by(CDEC))

# Add in historical start dates earlier than CDEC

# C7A CDEC data starts in 2002, actually began in 1984
# D6A CDEC data starts in 1994, actually began in 1983
# D10A CDEC data starts in 1988, actually began in 1984
# D12A CDEC data starts in 1995, actually began in 1983
# D24A CDEC data starts in 2003, actually began in 1983
# P8A CDEC data starts in 2000, actually began in 1983

# Remove rows with no measurements for these stations
df_CWQ <- df_CWQ %>% 
  filter(!(CDEC == "MSD" & Year <= 2001)) %>% 
  filter(!(CDEC == "MRZ" & Year <= 1993)) %>%
  filter(!(CDEC == "MAL" & Year <= 1987)) %>%
  filter(!(CDEC == "ANH" & Year <= 1994)) %>%
  filter(!(CDEC == "RVB" & Year <= 2002)) %>%
  filter(!(CDEC == "RRI" & Year <= 1999))

# Create a new df for each of these stations giving active measurements
df_C7A <- tibble(
  Year = seq(1984,2001),
  CombinedID = "C7-C7A",
  CDEC = "MSD",
  Study = "Continuous WQ",
  Measurements = 100
)

df_D6A <- tibble(
  Year = seq(1984,1993),
  CombinedID = "D6-D6A",
  CDEC = "MRZ",
  Study = "Continuous WQ",
  Measurements = 100
)

df_D10A <- tibble(
  Year = seq(1983,1987),
  CombinedID = "D10-D10A",
  CDEC = "MAL",
  Study = "Continuous WQ",
  Measurements = 100
)

df_D12A <- tibble(
  Year = seq(1983,1994),
  CombinedID = "D12-D12A",
  CDEC = "ANH",
  Study = "Continuous WQ",
  Measurements = 100
)

df_D24A <- tibble(
  Year = seq(1983,2002),
  CombinedID = "D24-D24A-NZ068",
  CDEC = "RVB",
  Study = "Continuous WQ",
  Measurements = 100
)

df_P8A <- tibble(
  Year = seq(1983,1999),
  CombinedID = "P8-P8A",
  CDEC = "RRI",
  Study = "Continuous WQ",
  Measurements = 100
)

# Add in the historical data years for these 6 stations
df_CWQ <- bind_rows(df_CWQ,df_C7A,df_D6A,df_D10A,df_D12A,df_D24A,df_P8A)

# Create a sequence of years from 1972 to 2023
years <- seq(1975, 2023)

df_intervals <- crossing(
  Year = years,
  CombinedID = df_stations$CombinedID,
  Study = c("Continuous WQ")
  )

# Add EMP dates to blank data frame
df_CWQ <- left_join(df_intervals,df_CWQ, join_by(Year,Study,CombinedID))

# Classify stations as active or inactive
df_CWQ <- df_CWQ %>% 
  mutate(Activity = case_when(Measurements > 0 ~ "Active",
                              TRUE ~ "Inactive"))

```


## Summarize Discrete Data by Component
```{r summarize, echo=FALSE}
# Summarize phyto data ---------------------------------------------------------
df_phyto_sum <- df_phyto %>% 
  group_by(StationID,Year) %>% 
  summarize(Measurements = sum(n())) %>% 
  mutate(StationID = str_replace_all(StationID, c("^S42$" ="NZS42"))) %>% 
  mutate(Study = "Phytoplankton")

df_phyto_EDI_sum <- df_phyto_EDI %>% 
  group_by(StationID,Year) %>% 
  summarize(Measurements = sum(n())) %>% 
  mutate(StationID = str_replace_all(StationID, c("^S42$" ="NZS42"))) %>% 
  mutate(Study = "Phytoplankton")

# Combine two phyto datasets 
df_phyto_sum <- bind_rows(df_phyto_sum, df_phyto_EDI_sum)

# Summarize WQ data ------------------------------------------------------------
df_DWQ_sum <- df_DWQ %>% 
  group_by(StationID,Year) %>% 
  summarize(Measurements = sum(n())) %>% 
  mutate(StationID = str_replace_all(StationID, c("^S42$" ="NZS42"))) %>% 
  mutate(Study = "Discrete WQ")

# Summarize zoop data ----------------------------------------------------------
df_zoop_sum <- df_zoop %>% 
  group_by(StationID,Year) %>% 
  summarize(Measurements = sum(n())) %>% 
  mutate(Study = "Zooplankton")

# Summarize benthic data -------------------------------------------------------
df_ben_sum <- df_ben %>% 
  group_by(StationID,Year) %>% 
  summarize(Measurements = sum(n())) %>% 
  mutate(Study = "Benthic")

```

## Fix Station Metadata
```{r metadata, echo=FALSE}
# Continuous WQ Metadata -------------------------------------------------------
# 
# # Create cross-walk table for C-WQ stations
# df_CDEC_metadata <- df_stations %>% select(CDEC,CombinedID,ShortName)
# 
# # Remove duplicate entries
# df_CDEC_metadata <- unique(df_CDEC_metadata)
# 
# # Add to C-WQ dataframe
# df_CWQ <- left_join(df_CWQ,df_CDEC_metadata, join_by(CDEC))

# Convert benthic station IDs --------------------------------------------------
df_ben_stations <- c("C3-L" = "C3",
                     "C3-R" = "C3",
                     "C3-C" = "C3",
                     "C7-C" = "C7",
                     "C7-L" = "C7",
                     "C7-R" = "C7",
                     "C9-C" = "C9",
                     "C9-L" = "C9",
                     "D10-C" = "D10",
                     "D10-L" = "D10",
                     "D10-R" = "D10",
                     "D11-C" = "D11",
                     "D11-L" = "D11",
                     "D11-R" = "D11",
                     "D12-C" = "D12",
                     "D14A-C" = "D14A",
                     "D14A-L" = "D14A",
                     "D14A-R" = "D14A",
                     "D16-C" = "D16",
                     "D16-L" = "D16",
                     "D19-C" = "D19",
                     "D19-L" = "D19",
                     "D19-R" = "D19",
                     "D24-L" = "D24",
                     "D26-C" = "D26",
                     "D26-L" = "D26",
                     "D26-R" = "D26",
                     "D28A-C" = "D28A",
                     "D28A-L" = "D28A",
                     "D28A-R" = "D28A",
                     "D4-C" = "D4",
                     "D4-L" = "D4",
                     "D4-R" = "D4",
                     "D41-C" = "D41",
                     "D41A-C" = "D41A",
                     "D6-C" = "D6",
                     "D6-L" = "D6",
                     "D6-R" = "D6",
                     "D7-C" = "D7",
                     "D7-L" = "D7",
                     "D7-R" = "D7",
                     "D8-C" = "D8",
                     "D9-C" = "D9",
                     "D9-R" = "D9",
                     "MD6-C" = "MD6",
                     "MD6-L" = "MD6",
                     "MD6-R" = "MD6",
                     "MD7-C" = "MD7",
                     "MD7-L" = "MD7",
                     "MD7-R" = "MD7",
                     "P8-C" = "P8",
                     "P8-L" = "P8",
                     "P8-R" = "P8"
                     )

# Replace benthic station names
df_ben_sum <- df_ben_sum %>% 
  mutate(StationID = str_replace_all(StationID, df_ben_stations))

# Remove duplicate entries
df_ben_sum <- unique(df_ben_sum)

```

## 

```{r combine discrete, echo=FALSE}
# Join all discrete elements together into a single data frame
df_EMP <- bind_rows(df_DWQ_sum,df_phyto_sum,df_zoop_sum,df_ben_sum,)

# Create new blank df for discrete data
df_intervals <- crossing(
  Year = years,
  StationID = df_stations$StationID,
  Study = c("Phytoplankton", "Discrete WQ","Zooplankton","Benthic")
  )

# Add EMP dates to blank data frame
df_EMP <- left_join(df_intervals,df_EMP, join_by(Year,StationID,Study))

# # Remove stations that aren't currently monitored
# df_active_stations <- df_EMP %>% 
#   group_by(StationID) %>% 
#   summarise(Measurements = sum(Measurements, na.rm = TRUE)) %>% 
#   filter(Measurements != 0) %>% 
#   select(!Measurements) %>% 
#   ungroup()
# 
# df_EMP <- df_EMP %>% 
#   filter(StationID %in% df_active_stations$StationID)

# Add additional station metadata
df_EMP <- left_join(df_EMP, 
                    df_stations,
                    join_by(StationID))

# Classify stations as active or inactive
df_EMP <- df_EMP %>% 
  group_by(CombinedID,Year,Study,CDEC,ShortName) %>% 
  summarise(Measurements = sum(Measurements, na.rm = TRUE)) %>%
  mutate(Activity = case_when(Measurements > 0 ~ "Active",
                              TRUE ~ "Inactive"))

```

## Combine Discrete and Continuous Data Frames
```{r combine, echo=FALSE}
# Combine discrete and continuous data
df_EMP <- bind_rows(df_EMP,df_CWQ)

# Add data for years 2022 (zoop) and 2023 (phyto, DWQ, zoop)
# Basically just assumes all active stations from 2021 are also active in 2022 and 2023

df_EMP <- df_EMP %>% filter(Year <= 2021)

df_EMP_2021 <- df_EMP %>% filter(Year == 2021)

df_EMP_2022 <- df_EMP_2021 %>% mutate(Year = case_when(Year == 2021 ~ 2022))
df_EMP_2023 <- df_EMP_2021 %>% mutate(Year = case_when(Year == 2021 ~ 2023))
df_EMP_2024 <- df_EMP_2021 %>% mutate(Year = case_when(Year == 2021 ~ 2024))

df_EMP <- bind_rows(df_EMP,df_EMP_2022,df_EMP_2023,df_EMP_2024)

# Make specific changes to add back in known gaps
df_EMP <- df_EMP %>% 
  mutate(Activity = case_when(Year == "2024" & CDEC == "IBS" ~ "Inactive",
                              TRUE ~ Activity)) %>% 
  mutate(Activity = case_when(Year > 2021 & CDEC == "ROR" ~ "Inactive",
                              TRUE ~ Activity)) 
  
# Add additional data frame for coloring
df_EMP <- df_EMP %>% 
  mutate(StudyActivity = case_when(Study == "Zooplankton" & Activity == "Active" ~ "Zoop-Active",
                                   Study == "Continuous WQ" & Activity == "Active" ~ "CWQ-Active",
                                   Study == "Discrete WQ" & Activity == "Active" ~ "DWQ-Active",
                                   Study == "Phytoplankton" & Activity == "Active" ~ "Phyto-Active",
                                   Study == "Benthic" & Activity == "Active" ~ "Benthic-Active",
                                   TRUE ~ "Inactive"))

# Set Sort Order for Plots
study_order <- c("Continuous WQ","Discrete WQ","Phytoplankton","Zooplankton","Benthic")
studyactivity_order <- c("Zoop-Active","CWQ-Active","DWQ-Active","Phyto-Active","Benthic-Active","Inactive")

df_EMP$Study <- factor(df_EMP$Study, levels = study_order)
df_EMP$StudyActivity <- factor(df_EMP$StudyActivity, levels = studyactivity_order)

df_test <- df_EMP %>% 
  filter(StudyActivity == "Zoop-Active") %>% 
  group_by(Year) %>% 
  summarise(ActiveStations = n())
         
```


## Plot Activity Timelines for Each Component
```{r plot, echo=FALSE}
# Plot benthic activity
ggplot(df_EMP %>% 
         group_by(CombinedID) %>% 
         filter(Study == "Benthic") %>%
         filter(Year >= 1980) %>% 
         filter(any(Activity == "Active")) %>%
         select(!Measurements) %>% 
         ungroup(), aes(x = Year, 
                        y = reorder(CombinedID, desc(CombinedID)), 
                        fill = Activity)) +
  geom_tile(height = 0.6) +
  scale_fill_manual(values = c("darkgreen","darkgray")) +
  facet_wrap(Study ~ ., ncol = 2) +
  labs(x = NULL,
       y = "Station Name",
       title = "EMP Benthic Monitoring Activity (1980-Present)")

ggsave(path = output,
       filename = "timeline-benthic.png",
       device = "png",
       scale=1.0,
       units="in",
       height=5,
       width=6.5,
       dpi="print")

# Plot Zooplankton Activity
ggplot(df_EMP %>% 
         group_by(CombinedID) %>% 
         filter(Study == "Zooplankton") %>%
         filter(any(Activity == "Active")) %>%
         select(!Measurements) %>% 
         ungroup(), aes(x = Year, 
                        y = reorder(CombinedID, desc(CombinedID)), 
                        fill = Activity)) +
  geom_tile(height = 0.6) +
  scale_fill_manual(values = c("darkgreen","darkgray")) +
  facet_wrap(Study ~ ., ncol = 2) +
  labs(x = NULL,
       y = "Station Name",
       title = "EMP Zooplankton Monitoring Activity (1975-Present)")

ggsave(path = output,
       filename = "timeline-zoop.png",
       device = "png",
       scale=1.0,
       units="in",
       height=9,
       width=6.5,
       dpi="print")

# Plot Discrete WQ Activity
ggplot(df_EMP %>% 
         group_by(CombinedID) %>% 
         filter(Study == "Discrete WQ") %>%
         filter(any(Activity == "Active")) %>%
         select(!Measurements) %>% 
         ungroup(), aes(x = Year, 
                        y = reorder(CombinedID, desc(CombinedID)), 
                        fill = Activity)) +
  geom_tile(height = 0.6) +
  scale_fill_manual(values = c("darkgreen","darkgray")) +
  facet_wrap(Study ~ ., ncol = 2) +
  labs(x = NULL,
       y = "Station Name",
       title = "EMP Discrete WQ Monitoring Activity (1975-Present)")

ggsave(path = output,
       filename = "timeline-D-WQ.png",
       device = "png",
       scale=1.0,
       units="in",
       height=9,
       width=6.5,
       dpi="print")

# Plot Phytoplankton Activity
ggplot(df_EMP %>% 
         group_by(CombinedID) %>% 
         filter(Study == "Phytoplankton") %>%
         filter(any(Activity == "Active")) %>%
         select(!Measurements) %>% 
         ungroup(), aes(x = Year, 
                        y = reorder(CombinedID, desc(CombinedID)), 
                        fill = Activity)) +
  geom_tile(height = 0.6) +
  scale_fill_manual(values = c("darkgreen","darkgray")) +
  facet_wrap(Study ~ ., ncol = 2) +
  labs(x = NULL,
       y = "Station Name",
       title = "EMP Phytoplankton Monitoring Activity (1975-Present)")

ggsave(path = output,
       filename = "timeline-phyto.png",
       device = "png",
       scale=1.0,
       units="in",
       height=9,
       width=6.5,
       dpi="print")

# Plot Continuous WQ Activity
ggplot(df_EMP %>% 
         group_by(CombinedID) %>% 
         filter(Study == "Continuous WQ") %>%
         filter(any(Activity == "Active")) %>%
         ungroup(), aes(x = Year, 
                        y = reorder(CombinedID, desc(CombinedID)), 
                        fill = Activity)) +
  geom_tile(height = 0.6) +
  scale_fill_manual(values = c("darkgreen","darkgray")) +
  facet_wrap(Study ~ ., ncol = 2) +
  labs(x = NULL,
       y = "Station Name",
       title = "EMP Continuous WQ Monitoring Activity (1975-Present)")

ggsave(path = output,
       filename = "timeline-CWQ.png",
       device = "png",
       scale=1.0,
       units="in",
       height=9,
       width=6.5,
       dpi="print")

```

## Individual Station Plots
```{r plot by station, echo=FALSE}

# Rename so as not to create folders
# df_EMP$CombinedID <- gsub("/","-",df_EMP$CombinedID)

# Use the black-and-white theme
theme_set(theme_bw())

# Create a ggplot2 theme
theme_update(
    #panel.grid.major = element_blank(),
    #panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "white", colour = NA),
    panel.background = element_rect(fill = "white", colour = NA),
    panel.border = element_rect(fill = NA, colour = "black"),
    strip.background = element_rect(fill = "gray", colour = "black"),
    legend.position = "none",
    legend.key = element_rect(fill = "white", colour = NA)
    )

# Create history plots for each year
stations <- unique(df_EMP$CombinedID) 
stations <- sort(stations, decreasing = F, na.last = T)

df_DEMP <- df_EMP %>% 
  filter(!Study == "Continuous WQ")

for (x in stations) {
  df_temp <- df_DEMP %>%
    filter(CombinedID == x)
  
  ggplot(df_temp,
         aes(x = Year, 
             y = reorder(Study, desc(Study)), 
             fill = StudyActivity)) +
    geom_tile(height = 0.6) +
    scale_fill_manual(values = c("Zoop-Active" = "#FF7F00", 
                                 "CWQ-Active" = "#984EA3",
                                 "DWQ-Active" = "#377EB8",
                                 "Phyto-Active" = "#4DAF4A",
                                 "Benthic-Active" = "#E41A1C",
                                 "Inactive" = "lightgray")) +
    labs(x = NULL,
         y = NULL,
         title = paste0("Discrete Monitoring - ",df_temp$ShortName)
         )
  
    ggsave(path = output,
         filename = paste0("site-history-at-",x,".png"), 
         device = "png",
         scale=1.0, 
         units="in",
         height=2,
         width=4.5, 
         dpi="print")
  
  rm(df_temp)
  
}

```

## Create data summary plots
```{r data summaries}
df_DWQ_sum <- df_DWQ %>% 
  mutate(Year = year(Date)) %>% 
  mutate(Month = month(Date, label = TRUE, )) %>% 
  relocate(c(Year,Month), .after = Date) %>% 
  group_by(StationID,Year,Month) %>% 
  summarise(TSSAvg = mean(TSS, na.rm = TRUE)) %>% 
  filter(!is.nan(TSSAvg))

test <- df_DWQ_sum %>% 
  filter(StationID %in% c("P8","C10","C10A","C9","C9A"))

ggplot() +
  geom_smooth(data = test,
              method = "loess",
              span = 0.8,
              aes(x = Year,
                  y = TSSAvg,
                  color = StationID))
```

