---
title: "Collinsville WQ Station Comparison"
author: "Ted Flynn"
date: "2024-05-23"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(lubridate)))
suppressWarnings(suppressMessages(library(janitor)))
suppressWarnings(suppressMessages(library(here)))
suppressWarnings(suppressMessages(library(cder)))

# Set output directory 
output <- here("01_WaterQuality","collinsville-wq","output")

# Set visual theme in ggplot
theme_set(theme_bw())

# Suppress summarise info
options(tidyverse.quiet = TRUE)
options(dplyr.summarise.inform = FALSE)

# Create date variables --------------------------------------------------------
start <- as.Date("2020-01-01")
end <- as.Date("2024-05-08")

```

## Import sonde data from CDEC

```{r import, echo=FALSE}
# Pull station data from CDEC
stations <- c("CLL","CSE")
 
df_WQ_all <- cdec_query(stations, sensors = c(100,25),
                        start.date = start,
                        end.date = end)

# Add more detailed description of each station
df_WQ_all <- df_WQ_all %>%
  mutate(Description = case_when(StationID == "CLL" ~ "C2 - Sac River @ Collinsville",
                                 StationID == "CSE" ~ "Collinsville on Sacramento River"
                                 ))

# Takes a long time to download from CDEC so save as RData file
save(df_WQ_all, file = here("01_WaterQuality","D1641-table5-sonde-uptime","df_WQ_all.RData"))

load(here("01_WaterQuality","collinsville-wq","df_WQ_all.RData"))

# Save new df for editing and cleaning
df_WQ <- df_WQ_all

```

## Clean Up Data
Create graphs that differentiate between different data types (Daily, Event, and Hourly) for SpC. 
```{r clean, echo=FALSE}
# Create new df for cleaning and remove duplicates
df_WQ <- df_WQ_all %>% distinct() # no rows removed

# Check CDEC column values
unique(df_WQ$DataFlag) # no values, not used for these stations

#quick check to see if there are the same number of samples per station per duration
table(df_WQ$SensorType, df_WQ$StationID, df_WQ$Duration)

# Filter out unneeded columns
df_WQ <- df_WQ %>% 
  select(!DataFlag) %>% # just a blank column
  select(!SensorNumber) %>% # CDEC codes for each analyte
  select(!SensorUnits) # we know what the units are

# Add additional date units for grouping and plotting
df_WQ <- df_WQ %>%
  mutate(Year = year(df_WQ$DateTime)) %>%
  mutate(Month = month(df_WQ$DateTime, label = TRUE)) %>%
  mutate(Date = date(df_WQ$DateTime))

# Rename output from CDEC for clarify
df_WQ <- df_WQ %>% 
  mutate(SensorType = str_replace(SensorType, "EL COND", "SpC")) %>% 
  mutate(SensorType = str_replace(SensorType, "TEMP W", "Water Temp"))

# Interpret content in the "Duration" column
unique(df_WQ$Duration) # H = hourly, E = event, D = daily

# Replace duration codes with more verbose descriptions
durations <- c("D" = "Daily","E" = "Event","H" = "Hourly")

df_WQ <- df_WQ %>% 
  mutate(Duration = str_replace_all(Duration, durations))

```

## Add Useful Metadata
```{r metadata, echo=FALSE}
# Add column distinguishing USBR and DWR stations
df_WQ <- df_WQ %>% 
  mutate(Agency = case_when(StationID == "CSE" ~ "DWR",
                            StationID == "CLL"  ~ "USBR"))


```

## Summarize WQ Data by Month
```{r summarize data, echo=FALSE}

# Filter out zeroes and NAs
df_WQ <- df_WQ %>% 
  filter(!is.na(Value)) %>% # Remove entries with an NA for the measured parameter
  filter(Value > 0) # Remove entries with a 0 or negative number for the measured parameter

# Create summary table for how many individual measurements exist for each station
df_WQ_m <- df_WQ %>% 
  group_by(StationID,Description,Month,SensorType,Duration) %>% 
  summarize(Total_Measurements = sum(n())) %>% 
  ungroup()

# Filter out redundant daily and hourly measurements
df_WQ <- df_WQ %>% filter(Duration == "Event")
  
```

## Compare Collinsville Stations
Graph comparisons of each Collinsville station.
```{r Collinsville, echo=TRUE}

# Use the black-and-white theme
theme_set(theme_bw())

# Set the theme
theme_update(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "white", colour = NA),
    panel.background = element_rect(fill = "white", colour = NA),
    panel.border = element_rect(fill = NA, colour = "black"),
    strip.background = element_rect(fill = "gray", colour = "black"),
    legend.position = "bottom",
    legend.key = element_rect(fill = "white", colour = NA)
    )

# Plot EC values
p_CLL_EC <- ggplot(df_WQ, aes(x = DateTime, y = Value, color=StationID)) +
  geom_line(data = subset(df_WQ, SensorType == "SpC"))

p_CLL_EC

```
```{r}
# Ideas from Rosie:
# Substract one from the other, plot the difference
# Add autoregressive term
# Calculate daily average
# Look at management triggers. Would changing stations make a different decision?


```

