---
title: "EMP Continuous WQ Metrics - 2023"
author: "Ted Flynn"
date: "2024-02-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
                      
suppressWarnings(suppressMessages(library(lubridate)))
suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(RColorBrewer)))
suppressWarnings(suppressMessages(library(janitor)))
suppressWarnings(suppressMessages(library(here)))

# Set output directory 
output <- here("04_Other","performance-metrics","output")

# Set visual theme in ggplot
theme_set(theme_bw())

# Suppress summarise info
options(tidyverse.quiet = TRUE)
options(dplyr.summarise.inform = FALSE)

# Define negative %in% operator
`%nin%` = Negate(`%in%`)
                      
```

## Read in raw data

```{r read input, echo = TRUE}
# Import C-EMP data files 
df_CEMP <- read_csv(file = here("04_Other","performance-metrics","data","2023_wagner.csv"))

## Combine date and time column
df_CEMP <- df_CEMP %>% 
  unite(exchange_time, c("visit_date","visit_time"), sep = " ") 

df_CEMP$exchange_time <- ymd_hms(df_CEMP$exchange_time,
                             tz = "US/Pacific")

# Check for missing dates
df_CEMP %>% filter(is.na(exchange_time)) # No missing dates

# Select only needed columns
df_CEMP <- df_CEMP %>% 
  select(site:exchange_time,analyte_name,rating)

# Check for station completeness
unique(df_CEMP$site)
summary(unique(df_CEMP$site)) # Lists all 15 sites

# Check for duplicated lines with 
df_duplicates <- janitor::get_dupes(df_CEMP) # 1 duplicated row

# Retain only distinct rows (remove duplicates)
df_CEMP <- distinct(df_CEMP)

```

```{r process CEMP data, echo = FALSE}
df_CEMP_w <- pivot_wider(df_CEMP, names_from = analyte_name, values_from = rating)

# Sort samples by date (early to late)
df_CEMP_w <- df_CEMP_w %>% 
  group_by(site) %>% 
  arrange(exchange_time) %>% 
  ungroup()

df_CEMP_w <- df_CEMP_w %>% 
  group_by(site) %>% 
  mutate(start_time = lag(exchange_time)) %>%
  ungroup()

df_CEMP_w <- df_CEMP_w %>% 
  mutate(start_time = case_when(is.na(start_time) ~ ymd_hms("2023-01-01 00:00:00"),
                          TRUE ~ ymd_hms(start_time)))

# Relocate Start Date column
df_CEMP_w <- df_CEMP_w %>% 
  relocate(start_time, .before = exchange_time)

# Calculate number of days between sonde exchanges
df_CEMP_w <- df_CEMP_w %>%
  mutate(days_rated = as.integer(exchange_time - start_time))

# Summarize rating data for graphing -------------------------------------------
df_CEMP_sum <- pivot_longer(df_CEMP_w, cols = `Water Temperature`:Turbidity,
                            values_to = "rating",
                            names_to = "parameter")

# Select needed data
df_CEMP_sum <- df_CEMP_sum %>% 
  select(site,days_rated:rating)

df_CEMP_sum <- df_CEMP_sum %>% 
  group_by(site, parameter, rating) %>% 
  summarize(total_days = sum(days_rated)) %>% 
  ungroup()

# Get ratings to sort in order good -> bad
rating.order <- c("Excellent","Good","Fair","Poor","MAL")

df_CEMP_sum$rating <- factor(as.character(df_CEMP_sum$rating), 
                             levels = rating.order)

# Check how many days each sonde was rated for 
df_CEMP_totals <- df_CEMP_sum %>% 
  group_by(site, parameter) %>%
  summarize(days_rated = sum(total_days)) %>%
  ungroup()


```

## Plots

```{r plot CEMP, echo = FALSE}

colors = c("darkgreen","darkblue","yellow3","darkred","purple")

p1 <- ggplot(data = df_CEMP_sum, aes(x = total_days, 
                                            y = parameter, 
                                            fill = rating)) +
  geom_bar(position = "stack",  
           width = .6, 
           stat = "summary", 
           fun = "sum") +
  scale_fill_manual(values = colors)

p1 +
  labs(x = "Rating of Data Collected (Days)",
       y = "Sensor",
       fill = "Sonde Rating",
       title = "EXO2 Sonde Probe Ratings - C-EMP - 2022 ") +
  facet_wrap(site ~ ., ncol = 5)

# Make plots without Turbidity ratings
p2 <- ggplot(data = df_CEMP_sum, aes(x = total_days, 
                                            y = parameter, 
                                            fill = rating)) +
  geom_bar(data = subset(df_CEMP_sum, parameter != "Turbidity"),
    position = "stack",  
           width = .6, 
           stat = "summary", 
           fun = "sum") +
  scale_fill_manual(values = colors)

p2 +
  labs(x = "Rating of Data Collected (Days)",
       y = "Sensor",
       fill = "Sonde Rating",
       title = "EXO2 Sonde Probe Ratings - C-EMP - 2023 ") +
  facet_wrap(site ~ ., ncol = 5)

ggsave(path = output,
       filename = "CEMP_sonde_scores_2023.pdf", 
       device = "pdf",
       scale=1.0, 
       units="in",
       height=6.5,
       width=9, 
       dpi="print")

```

