Title: Combine 20 - 22 fluoroprobe data

Date: 10/23

```{r}
library(tidyverse)
library(lubridate)
library(glue)
```

```{r}
fl_20 <- read_csv('03_Phyto/fluoroprobe-data-cleaning/Fluoroprobe Data 2020 1 minute intervals.csv',
                  col_types = cols(`PAR1_umol_m-2_s-1` = col_number(), `PAR2_umol_m-2_s-1` = col_number()))

fl_21 <- read_csv('03_Phyto/fluoroprobe-data-cleaning/Fluoroprobe Data 2021 1 minute intervals.csv',
                  col_types = cols(`PAR1_umol_m-2_s-1` = col_number(), `PAR2_umol_m-2_s-1` = col_number()))

fl_22 <- read_csv('03_Phyto/fluoroprobe-data-cleaning/Fluoroprobe Data 2022 1 minute intervals.csv',
                  col_types = cols(`PAR1_umol_m-2_s-1` = col_number(), `PAR2_umol_m-2_s-1` = col_number()))

df_fl <- rbind(fl_20, fl_21, fl_22)

nrow(fl_20)+nrow(fl_21)+nrow(fl_22)

df_fl$Date <- as.Date(df_fl$Date, format = '%m/%d/%Y')

df_fl$DateTime <- as_datetime(paste(df_fl$Date, df_fl$Time))

test <- df_fl
test$roundtime <- round_date(test$DateTime, unit='15 mins')
test <- test %>% select(select = -c(Date, Time, DateTime))

test <- test %>%
  group_by(roundtime) %>%
  summarise(across(everything(), ~ mean(.x, na.rm = TRUE))) %>%
  rename(DateTime = roundtime)

test2 <- test
test2$DateTime <- round_date(test2$DateTime, unit = '1 month')

test2 <- test2 %>%
  group_by(DateTime) %>%
  summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)))# %>%

df_fl <- df_fl %>% select(select = -c(Date, Time))
#  pivot_longer(cols = 'GreenAlgae_2ug_L':'PAR2_umol_m-2_s-1')
# 
# test <- test %>%
#   pivot_longer(cols = 'GreenAlgae_2ug_L':'PAR2_umol_m-2_s-1')
```

```{r}
# ggplot(test2, aes(DateTime, value, color = name)) +
#   geom_point() +
#   geom_line() +
#   facet_wrap(~ groups, ncol = 3, scales = 'free') +
#   theme(legend.position = 'none')
# 
# ggsave('03_Phyto/fluoroprobe-data-cleaning/plots/QC_1.png', width = 12, height = 7)
```

```{r}
# df_dt <- test2 %>% filter(year(DateTime) == 2022)

df_mavg <- test2

graph_monyear <- function(df, year, month, param){
  df_day <- df_fl %>% filter(year(DateTime) == year, month(DateTime) == month)
  
  if(nrow(df_day) == 0){
    return('no data')
  }
  plt <- ggplot(df_day, aes(DateTime, .data[[param]])) +
    geom_point(shape = 21) +
    geom_line() +
    facet_wrap( ~ day(DateTime), ncol = 2, scales = 'free') +
    labs(title = paste(month.abb[month], year)) +
    theme_bw()
  
    ggsave(glue('03_Phyto/fluoroprobe-data-cleaning/plots/day/QC_{param}_{year}_{month}.png'), width = 10, height = 7)
}



graph_all <- function(df, param){
  plt <- ggplot(df, aes(DateTime, .data[[param]])) +
    geom_point() +
    geom_line() +
    theme_bw()
  
  ggsave(glue('03_Phyto/fluoroprobe-data-cleaning/plots/QC_month_{param}.png'), width = 6, height = 5)
}
```

```{r}
for (param in names(df_mavg)[4:length(df_mavg)]){
  graph_all(df_mavg, param)
}

for (param in names(df_fl)[4:length(df_day)]){
  for (year in unique(year(df_fl$DateTime))){
    for (month in unique(month(df_fl$DateTime))){
      graph_monyear(df_fl, year, month, param)   
    }
  }
}
```

