---
title: "clean_yearly_horz_ACCESS"
output: html_document
---

2/18/2025

initial cleaning of horizontal WQ data extracted from access database

Title: Phycoprobe Data - Monthly Cleaning

By: Perry and Craig Stuart

```{r}
# ---
# EDIT THIS
# ---

# declare the run year of interest  
year <- 2017
```

```{r}
# ---
# CODE STARTS HERE
# ---

# import packages
library(tidyverse)
library(lubridate)
library(readxl)
options(digits = 10)
source('03_Phyto/phycoprobe/functions/phyco_funcs.R')

# read in run names and regions
df_names <- read_csv('03_Phyto/phycoprobe/supp_files/run_names.csv', show_col_types = FALSE)

# obtain all file paths and create combo df
fp_all_wq <- archive_path(year, 'MOPED')

df_combo <- create_combo_df(fp_all_wq)

df_list <- list()
# df_rmlist <- list()

# run code for all combos
for(i in 1:nrow(df_combo)){
  # define variables
  month <- df_combo[i,]$month
  run <- df_combo[i,]$run
  
  print(glue::glue('month: {month} and run: {run}'))
  
  # read in WQ data
  fp_wq <- data_path(run, month, year, type = 'MOPED')
  
  df_wq <- read_csv(fp_wq,
                    show_col_types = TRUE)

  #df_wq <- df_wq %>% filter(Equipment == 'EXO Horizontal')
  df_wq$Current_Date <- as.Date(df_wq$Current_Date, format="%m/%d/%Y")
  df_wq$Current_Date <- format(df_wq$Current_Date, "%Y-%m-%d")

  df_wq$Current_Time <- as.POSIXct(df_wq$Current_Time, format = "%H:%M:%S")

  df_wq$Combined_DateTime <- as.POSIXct(paste(df_wq$Current_Date, format(df_wq$Current_Time, "%H:%M:%S")), format="%Y-%m-%d %H:%M:%S")

  df_wq <- df_wq %>% 
    select(-Current_Date, -Current_Time)
  

  #df_wq$TimeStamp <- parse_date_time(df_wq$TimeStamp, c('mdY HMS', 'mdY HM'))
  #df_wq$TimeStamp <- as.POSIXct(df_wq$TimeStamp, format = '%m/%d/%Y %H:%M:%S')
  
  #df_wq$Analyte <- paste0(df_wq$Header,'_',df_wq$Unit)

  # remove rows where Longitude&Latitude OR TimeStamp repeat for a given analyte
  
  df_wq <- df_wq %>%
    group_by(Header) %>%
    filter(!((Latitude %in% Latitude[duplicated(Latitude)] & 
              Longitude %in% Longitude[duplicated(Longitude)]) | 
             Combined_DateTime %in% Combined_DateTime[duplicated(Combined_DateTime)])) %>%
    ungroup()

  # df_wq <- df_wq %>%
  #   subset(select = c(Longitude, Latitude, TimeStamp, Analyte, Value)) %>%
  #   rename(DateTime = TimeStamp) %>%
  #   pivot_wider(
  #     names_from = Analyte,
  #     values_from = Value
  #   ) %>%
  #   filter(!if_any(everything(), ~ .x == 0 | is.na(.x)))

  df_wq <- df_wq %>%
    mutate(RoundedDateTime = round_date(DateTime, 'minute')) %>%
    mutate(TimeDiff = abs(as.numeric(difftime(DateTime, RoundedDateTime, units = 'secs')))) %>%
    group_by(RoundedDateTime) %>%
    slice_min(order_by = TimeDiff, n = 1, with_ties = FALSE) %>%
    ungroup() %>%
    select(-c(DateTime, TimeDiff)) %>%
    rename(DateTime = RoundedDateTime)
  
  # filter out rows around Antioch
  lat_min <- 38.016249
  lat_max <- 38.023349
  lon_min <- -121.759586
  lon_max <- -121.746626

  df_wq <- df_wq %>%
  filter(!(Latitude >= lat_min & Latitude <= lat_max &
             Longitude >= lon_min & Longitude <= lon_max))
  
  # filter analytes
  # df_wq <- df_wq %>%
  #   filter(`SPC_uS/cm` > 50,
  #          WT_C > 0,
  #          `PH_pH Units` > 0,
  #          FNU_FNU > 0,
  #          `FLUOR_ug/L` > 0,
  #          FLUORRFU_RFU > 0,
  #          `DO_mg/L` > 0,
  #          `DOSAT_% SAT` > 0
  #          )

  # convert date/time col back to character
  df_wq$DateTime <- as.character(df_wq$DateTime)
  
  # bind to df list
  df_list[[i]] <- df_wq
  #df_rmlist[[i]] <- df_removed
}

# Combine all data frames into one
df_final <- bind_rows(df_list)
#df_remove <- bind_rows(df_rmlist)

df_final <- df_final %>%
  arrange(DateTime)

  df_final <- df_final %>%
    filter(`SPC_uS/cm` > 50,
           WT_C > 0,
           `PH_pH Units` > 0,
           FNU_FNU > 0,
           `FLUOR_ug/L` > 0,
           FLUORRFU_RFU > 0,
           `DO_mg/L` > 0,
           `DOSAT_% SAT` > 0
           )

# df_remove <- df_remove %>%
#   arrange(TimeStamp)

write_csv(df_final, 'C:/Users/cstuart/Desktop/Annual Moped Files - Temp/MOPED_2024_combined_final.csv')

#write_csv(df_final, 'C:/Users/sperry/Desktop/wq_test_19.csv')

# write_csv(df_remove, 'C:/Users/sperry/Desktop/wq_test_remove.csv')
```