---
title: "MOPED TEST"
author: "Craig Stuart"
date: "2024-10-21"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(readr)
library(lubridate)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
directory_path <- "C:/Users/cstuart/Desktop/MOPED_Jan2024/data"
```

#Pull list of files from folder
```{r}
file_list <- list.files(path = directory_path, pattern = ".csv", full.names = TRUE)
```

#combine list of files after removing first two lines
```{r}
combined_data <- file_list %>% 
  lapply(read_csv, skip = 2) %>% 
  bind_rows()
```

#Remove rows with EXO Vertical, and unwanted columns
```{r}
text_to_remove <- "EXO Vertical"

clean_data <- combined_data %>% 
  filter(Equipment != text_to_remove) %>% 
  select(-Station, -SerialNumber, -Flag, -Tow, -Interpolated, -...18)
```

```{r}

filtered_data <- clean_data %>% 
  filter(!(second(TimeStamp) > 5 & second(TimeStamp) < 55))
```



#Reformat Date/Time and split into two columns
```{r}
clean_data$`TimeStamp` <- as.POSIXct(clean_data$`TimeStamp`, format = '%m/%d/%Y %H:%M:%S')

data <- clean_data %>% 
  mutate(Date = as.Date(TimeStamp), Time = format(TimeStamp, "%H:%M:%S") ) %>% 
  select(-TimeStamp)



filtered_data <- data %>% 
  filter(!(second(Time) > 5 & second(Time) < 55))

```

```{r}
data_time <- data %>% 
  mutate(
    NumericTime = hour(hms(Time)) * 3600 + minute(hms(Time)) * 60 + second(hms(Time))
  )

filtered_data <- data %>% filter(!(second(Time) > 5 & second(Time) < 55))
```






```{r}
#clean_data <- clean_data %>%
  #mutate('TimeStamp' = round_date('TimeStamp', unit='1 minute')) %>%
 # group_by('TimeStamp') %>%
 # summarize_all(~round(mean(., na.rm = TRUE),2))
```


```{r}
#write.csv(clean_data, file = "C:/Users/cstuart/Desktop/MOPED_Jan2024/data/clean_data.csv", row.names = FALSE)
```




